package project.lms_rikkei_edu.modules.notification.enums;

public enum NotificationType {
    FORUM_REPLY,
    FORUM_POST,
    QUIZ_PUBLISHED,
    SUBMISSION_GRADED,
    ASSIGNMENT_PUBLISHED,
    ASSIGNMENT_SUBMITTED,
    CERTIFICATE_ISSUED,
    COURSE_ENROLLMENT,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    GROUP_SCHEDULE_CHANGED,
    GROUP_STARTING_SOON,
    GROUP_STARTED,
    GROUP_ENDING_SOON,
    GROUP_ENDED,
    GROUP_DELETED,
    COURSE_APPROVED,
    SYSTEM_ANNOUNCEMENT,
    AI_SOURCE_INDEXED,
    AI_SOURCE_FAILED
}
